sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bahaa129/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true bahaa129/react-app -react npm run test